# This configuration file should only include **pre-existing** security
# errors and warnings related to GitHub workflow files that we intend to
# fix later on.
#
# ⚠️ Please do not add any new zizmor findings to this file. ⚠️
#
# If a potential security vulnerability does not necessitate a fix
# (for example, if `uses:` invokes an unpinned action from a trusted
# organization), then append `# zizmor: ignore[unpinned-uses]` to
# the reported line (with `unpinned-uses` replaced by the appropriate
# error code).
#
# Include both the row and column numbers below so that we ignore
# specific errors. Doing this makes this configuration brittle, which
# has the benefit(?) that we will be reminded of these errors when
# modifying the workflow files.
#
# Documentation: https://woodruffw.github.io/zizmor/usage/#ignoring-results

rules:
  excessive-permissions:
    ignore:
    - create-release-issue.yml:11:3
    - changelog.yml:9:3
    - changelog.yml:10:3
    - comment-on-pr.yml:8:3
    - mint-release.yml:17:3
    - unlabel-pr-after-merge.yml:8:3
    - update-pinned-reqs.yml:9:3
  template-injection:
    ignore:
    - create-release-issue.yml:21:7
    - mint-release.yml:41:7
    - mint-release.yml:47:7
    - mint-release.yml:53:7
    - mint-release.yml:61:7
    - mint-release.yml:66:7
  use-trusted-publishing:
    ignore:
    - publish-to-pypi.yml:36:7
