name: Label PR

# The labels to be added are defined in .github/labeler.yml

# See https://github.com/actions/labeler#permissions
on:
- pull_request_target  # zizmor: ignore[dangerous-triggers]

jobs:
  labeler:
    name: Add labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v5
